<?php

return [
'company' => '',
'street' => '',
'address_2' => '',
'town' => '',
'county' => '',
'country' => '',
'postcode' => '',
'phone_number' => '',
'phone' => '',
'fax' => '',
'email' => '',
'supportEmail' => '',
'returnsemail' => '',
'ccemail' => '',
'appname' => '',
'sandbox' => '1',
'maintenance' => '1',
'manager' => '100',
'facebook' => '',
'twitter' => '',
'google' => '',
'instagram' => '',
'monday' => '9am - 5pm',
'tuesday' => '9am - 5pm',
'wednesday' => '9am - 5pm',
'thursday' => '9am - 5pm',
'friday' => '9am - 5pm',
'saturday' => '9am - 1pm',
'sunday' => 'Closed',
'logo' => 'logo.png'
'admindir' => 'admin'
];
